image: node:20.11.0

stages:
  - prepare
  - deploy
  - confidence-check

before_script:
  - apt-get update -qy
  - apt-get install -y default-jre
  - apt-get update
  - apt-get install -y wget unzip curl

  # Install or update Google Chrome
  - CHROME_VERSION="122.0.6261.18"
  # Install Google Chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb || apt --fix-broken install -y
  - google-chrome-stable --version

prepare:
  stage: prepare
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

pages:
  stage: deploy
  dependencies:
   - prepare
  script:
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


e2e:firefox:
  stage: confidence-check
  dependencies:
   - prepare
  services:
    - selenium/standalone-firefox
  script:
    - npm run confidence-check --host=selenium__standalone-firefox
