image: node:21.6.1

stages:
  - prepare
  - deploy
  - confidence-check

prepare:
  stage: prepare
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

pages:
  stage: deploy
  dependencies:
   - prepare
  script:
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


e2e:firefox:
  stage: confidence-check
  dependencies:
   - prepare
  services:
    - selenium/standalone-firefox
  script:
    - npm run confidence-check --host=selenium__standalone-firefox

e2e:chrome:
  stage: confidence-check
  dependencies:
   - prepare
  services:
    - selenium/standalone-chrome
  script:
    - npm run confidence-check --host=selenium__standalone-chrome