# this workflow was derived from https://codeberg.org/r-codeberg/woodpecker-ci
# please file bug reports and feature requests to help it improve!

matrix:
  IMAGE: 
    - node:latest

when:
  - branch: "${CI_REPO_DEFAULT_BRANCH}"
    event: push
  - event: pull_request
  - event: tag

variables:
  site_config: &site_config
    - export WOODPECKER_TMP=/woodpecker/tmp

  step_pkgdown: &pkgdown
    - name: pkgdown
      image: ${IMAGE}
      # depends_on: [setup]
      commands:
        - npm i
        - npm run build
        - pwd
        - mkdir ${WOODPECKER_TMP}/pages
        - ls -lt dist
        - cp -r dist/* $${WOODPECKER_TMP}/pages
        - ls $${WOODPECKER_TMP}/pages

  step_deploy: &deploy
    - name: deploy
      image: codeberg.org/sugar700/plugin-codeberg-pages-deploy:latest
      depends_on: [pkgdown]
      settings:
        folder: dist
        ssh_key:
          from_secret: deploy_ssh_key

steps:
  # - <<: *setup
  # - <<: *check
  # - <<: *test
  - <<: *pkgdown
  - <<: *deploy
